[tool.poetry]
name = "magicmatching"
version = "0.1.0"
description = ""
authors = []
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"

[build-system]
requires = ["poetry-core==1.1.0"]
build-backend = "poetry.core.masonry.api"
