#!/bin/bash

set -o allexport
source ../.env
set +o allexport

export PORT=3431

CAL_DIR=$THIRD_PARTY_DIR/cal.com

cd $CAL_DIR/apps/web

# Direct path to next used here so that `supervisorctl stop` works as expected
exec $NODE_PATH $CAL_DIR/node_modules/next/dist/bin/next start
